name: Deploy to EC2 via SCP

on:
  workflow_dispatch:  # This triggers the workflow manually

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner for the job

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug Hostname
      run: echo "EC2 Host: ${{ secrets.EC2_HOST }}"

